In [2]:
import pandas as pd

root = 'feb_2023'
tv_path = root+"\\"+"tv.csv"
df = pd.read_csv(tv_path)

In [10]:
df.info

<bound method DataFrame.info of          id  metascore        release_date  sort_no  \
0     72329         99    October 26, 2016        1
1       738         99       July 19, 1995        2
2     51124         99  September 19, 1995        3
3       740         99      March 15, 1998        4
4     46560         99       July 15, 2012        5
...     ...        ...                 ...      ...
3293  44901         19     January 3, 2012     3294
3294   9335         18    November 6, 2005     3295
3295  52179         17     October 1, 2014     3296
3296  51282         15  September 17, 2013     3297
3297  11227         13   February 18, 2007     3298

                                                summary  \
0     Daniel tries to start a new life outside of Pa...
1     Comic Garry Shandling draws upon his own talk ...
2     One of several crime and law dramas created by...
3     Comic Garry Shandling draws upon his own talk ...
4     The final season for the award-winning drama b...
...                                                 ...
3293  After they are laid off, Lee Standish (Ben Kol...
3294  This killer-storm disaster sequel to "Category...
3295  Lt. Beth Davis (Maggie Q) leads the Threat Ass...
3296  In this live-action comedy from producer Seth ...
3297  The right-wing answer to "The Daily Show With ...

                                           title user_score
0                              Rectify: Season 4        8.2
1               The Larry Sanders Show: Season 4        4.8
2                           Murder One: Season 1        4.6
3               The Larry Sanders Show: Season 6        4.1
4                         Breaking Bad: Season 5        9.7
...                                          ...        ...
3293                          Work It : Season 1        0.9
3294  Category 7: The End of the World: Season 1        3.7
3295                           Stalker: Season 1        7.4
3296                              Dads: Season 1        3.8
3297            The 1/2 Hour News Hour: Season 1        2.8

[3298 rows x 7 columns]>

In [17]:
df.drop('summary', axis=1, inplace=True)
df

,id,metascore,release_date,sort_no,title,user_score
0,72329,99,"October 26, 2016",1,Rectify: Season 4,8.2
1,738,99,"July 19, 1995",2,The Larry Sanders Show: Season 4,4.8
2,51124,99,"September 19, 1995",3,Murder One: Season 1,4.6
3,740,99,"March 15, 1998",4,The Larry Sanders Show: Season 6,4.1
4,46560,99,"July 15, 2012",5,Breaking Bad: Season 5,9.7
...,...,...,...,...,...,...
3293,44901,19,"January 3, 2012",3294,Work It : Season 1,0.9
3294,9335,18,"November 6, 2005",3295,Category 7: The End of the World: Season 1,3.7
3295,52179,17,"October 1, 2014",3296,Stalker: Season 1,7.4
3296,51282,15,"September 17, 2013",3297,Dads: Season 1,3.8
3297,11227,13,"February 18, 2007",3298,The 1/2 Hour News Hour: Season 1,2.8

In [19]:
user_score = df[(df['metascore']>=80) & (df['user_score']!='tbd')].sort_values('user_score', ascending=False)
user_score.to_csv('shows\\top shows by user_score.csv')