In [24]:
import pandas as pd

# df = pd.read_csv(r'D:\code\deep learning projects\metacritic analysis\all_time_tv_shows_metacritic.csv')
# df

In [25]:
import pandas as pd

In [27]:

root = 'feb_2023'
tv_path = root+"\\"+"tv.csv"
df = pd.read_csv(tv_path)

In [28]:
df.info

<bound method DataFrame.info of          id  metascore        release_date  sort_no  \
0     72329         99    October 26, 2016        1
1       738         99       July 19, 1995        2
2     51124         99  September 19, 1995        3
3       740         99      March 15, 1998        4
4     46560         99       July 15, 2012        5
...     ...        ...                 ...      ...
3293  44901         19     January 3, 2012     3294
3294   9335         18    November 6, 2005     3295
3295  52179         17     October 1, 2014     3296
3296  51282         15  September 17, 2013     3297
3297  11227         13   February 18, 2007     3298

                                                summary  \
0     Daniel tries to start a new life outside of Pa...
1     Comic Garry Shandling draws upon his own talk ...
2     One of several crime and law dramas created by...
3     Comic Garry Shandling draws upon his own talk ...
4     The final season for the award-winning drama b...
...                                                 ...
3293  After they are laid off, Lee Standish (Ben Kol...
3294  This killer-storm disaster sequel to "Category...
3295  Lt. Beth Davis (Maggie Q) leads the Threat Ass...
3296  In this live-action comedy from producer Seth ...
3297  The right-wing answer to "The Daily Show With ...

                                           title user_score
0                              Rectify: Season 4        8.2
1               The Larry Sanders Show: Season 4        4.8
2                           Murder One: Season 1        4.6
3               The Larry Sanders Show: Season 6        4.1
4                         Breaking Bad: Season 5        9.7
...                                          ...        ...
3293                          Work It : Season 1        0.9
3294  Category 7: The End of the World: Season 1        3.7
3295                           Stalker: Season 1        7.4
3296                              Dads: Season 1        3.8
3297            The 1/2 Hour News Hour: Season 1        2.8

[3298 rows x 7 columns]>

In [29]:
df.drop('summary', axis=1, inplace=True)
df

,id,metascore,release_date,sort_no,title,user_score
0,72329,99,"October 26, 2016",1,Rectify: Season 4,8.2
1,738,99,"July 19, 1995",2,The Larry Sanders Show: Season 4,4.8
2,51124,99,"September 19, 1995",3,Murder One: Season 1,4.6
3,740,99,"March 15, 1998",4,The Larry Sanders Show: Season 6,4.1
4,46560,99,"July 15, 2012",5,Breaking Bad: Season 5,9.7
...,...,...,...,...,...,...
3293,44901,19,"January 3, 2012",3294,Work It : Season 1,0.9
3294,9335,18,"November 6, 2005",3295,Category 7: The End of the World: Season 1,3.7
3295,52179,17,"October 1, 2014",3296,Stalker: Season 1,7.4
3296,51282,15,"September 17, 2013",3297,Dads: Season 1,3.8
3297,11227,13,"February 18, 2007",3298,The 1/2 Hour News Hour: Season 1,2.8

In [34]:
user_score = df[(df['metascore']>=80) & (df['user_score']!='tbd')].sort_values(['user_score', 'metascore'], ascending=[False, False])
user_score.head(20)

,id,metascore,release_date,sort_no,title,user_score
4,46560,99,"July 15, 2012",5,Breaking Bad: Season 5,9.7
33,88449,95,"July 11, 2022",34,Better Call Saul: Season 6.5,9.7
21,43234,96,"July 17, 2011",22,Breaking Bad: Season 4,9.5
37,87941,94,"April 18, 2022",38,Better Call Saul: Season 6,9.4
465,12165,89,"March 21, 2010",123,Breaking Bad: Season 3,9.4
673,77044,87,"August 6, 2018",175,Better Call Saul: Season 4,9.2
677,73561,87,"April 10, 2017",179,Better Call Saul: Season 3,9.2
213,12164,84,"March 8, 2009",314,Breaking Bad: Season 2,9.2
9,5672,98,"September 19, 2004",10,The Wire: Season 3,9.1
10,5673,98,"September 10, 2006",11,The Wire: Season 4,9.1
15,1128,97,"March 4, 2001",16,The Sopranos: Season 3,9.1
18,2330,96,"April 8, 1990",19,Twin Peaks: Season 1,9.1
26,66012,96,"October 12, 2015",27,Fargo: Season 2,9.1
38,52129,94,"April 6, 2014",39,Game of Thrones: Season 4,9.1
39,7404,94,"October 6, 2006",40,Battlestar Galactica (2003): Season 3,9.1
46,6506,93,"March 6, 2005",47,Deadwood: Season 2,9.1
57,13998,92,"July 25, 2010",58,Mad Men: Season 4,9.1
58,5580,92,"March 12, 2002",59,The Shield: Season 1,9.1
87,43388,91,"February 9, 2011",88,Justified: Season 2,9.1
90,44088,91,"January 1, 2012",91,Sherlock: Season 2,9.1

In [ ]:
user_score.to_csv('shows\\top shows by user_score.csv')